# Generated by Django 6.1.1 on 2026-09-27 11:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-transaction_date'], name='transaction_user_id_64ff44_idx'), models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_98a6b3_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_a385c1_idx')],
            },
        ),
    ]
